### PR TITLE
Style search

### PR DESCRIPTION
**Pull request by Cuponk**
added extra styling and a default search to the games index page, also i guess the code for the year and friends wish list and library were all broken so those were fixed, doing reviews

### CODE REVIEW

**Comment by juliouribe** [comment]
Don't forget to request Weyman and I as reviewers. Do you have a screenshot of what it looks like now?

**Comment by Cuponk** [comment]
oh yeah whoops, heres the screen shot 
CleanShot 2023-09-13 at 17 22 47@2x

all the default search does is just search for games release this year

**Review by juliouribe — APPROVED** [review]
Nice. Looks good to me. At a company a software engineer would recommend putting the jwtFetch functions into a store file but its fine with me. Let's get greenlit as soon as possible!

**Comment by wleung4** [comment]
Search looks nice. Nice work

**Review by wleung4 — APPROVED** [review]

**Pull request merged**
