### PR TITLE
add heroku host

### PR DESCRIPTION
**Pull request by Cuponk**
added a proc file for hosting to heroku, also tried a test build and heroku didn't like the react icons package for some reason so I changed them to the font awesome icons, functionality is still the same. Hopefully this will work, app academy open is down for some reason so I cant access the tutorial

### CODE REVIEW

**Comment by juliouribe** [comment]
Does heroku hosting work with these changes? I think we might need to add react icons as a dependency to get that to work but I'm down to use Font Awesome as well if its the same.

**Comment by Cuponk** [comment]
I'm not sure, I'm gonna try to host this branch to test. I was trying to do a build and it was throwing an error that it wasn't installed but it might just be some weird user error on my end

**Review by wleung4 — COMMENTED** [review]
I believe for the aggregate rating part of game show, I used the react icon on around line 141.

**Comment by Cuponk** [comment]
ok it works now

**Review by wleung4 — APPROVED** [review]

**Pull request merged**
