### PR TITLE
change color

### PR DESCRIPTION
**Pull request by Cuponk**
just changing the color from black to purple
CleanShot 2023-09-12 at 14 08 52@2x

### CODE REVIEW

**Comment by wleung4** [comment]
Looks good, I think reducing the individual reviews gameplay, visuals, story, and stars font size a little smaller would look better relative to the page

**Comment by juliouribe** [comment]
I think we still need more styling. Maybe use some border radius on the edges or use a gray line in between instead of a full rectangular border? The text of the review also seems a little off. Maybe the text review needs a header.

Screen Shot 2023-09-12 at 2 31 51 PM

**Comment by Cuponk** [comment]
heres how it looks now 
CleanShot 2023-09-13 at 20 34 46@2x

**Review by juliouribe — APPROVED** [review]
Looks great

**Pull request merged**
